姓名: 许恒珲
url: https:xiaohang007.github.io/

排除:[: bibble README.md,制作文件，截图.png

# 使用程序模块对代码片段进行颜色化
荧光笔: pygments

#博客文章的路径结构。
permalink: /blog/:::年份/月份/日期/::​::​::title.html
编码: utf-8
#"人"页面上的章节。
角色:
  - 键: 学院
姓名: 教师 Faculty
  - 键: 毕业生
姓名: 研究生
  - 键: 城堡
姓名: 本科生 Undergraduate Students
  - 键: 同事
姓名: 合作者 Collaborators


#头版新闻报道的数量。
头版新闻: 8

#链接的基本路径名。
基础:'': ​

#为_projects文件夹创建页面
收集:
项目:
输出: 真实的

#导航栏链接。
航行:
  - title: 主页 Home
    link: /
  - title: 科研项目 Research
    link: /research.html
  - title: 论文 Publications
    link: /publications.html
